### ISSUE TITLE
Not auto restarting  on HASSIO reboot

### ISSUE THREAD

**Issue by aptonline** [hassio-addons/addon-homebridge#15]
## Problem/Motivation

> Homebridge isn’t auto restarting if host is rebooted

## Expected behavior

> Homebridge should restart if Auto is selected.

## Actual behavior

> homebridge doesn’t start, have to manually start addon.

## Steps to reproduce

> Make sure homebridge is installed and started, reboot host (HASSIO) check homebridge add on once started up. Should show the start button.

## Proposed changes

> fix so auto restarts after host reboot.

**Comment by frenck** [comment]
@aptonline I'm not sure what the problem is you are describing. 
Whether or not the add-on starts on boot, is controlled by Hass.io, not the add-on.

There is actually a toggle on each add-on in the Hass.io panel that controls the automatic start.

Do you still experience this problem at this moment?

**Comment by frenck** [comment]
Question is running stale. Feel free to re-open this issue.

**Comment by disrupted** [comment]
I am having a similar issue. The "boot" toggle inside Hass.io's contol panel for Homebridge is set to _auto_, still often it doesn't start automatically.

**Comment by frenck** [comment]
@disrupted Please file a bug report with Hass.io. This is not something the add-on is able to control.
