### ISSUE TITLE
Ver 1.0.3 HomeAssistant Error adding xiao mi socket

### ISSUE THREAD

**Issue by leapp** [hassio-addons/addon-homebridge#42]
/usr/lib/node_modules/homebridge-homeassistant/accessories/switch.js:35
        .setValue(newState.state === 'on', null, 'internal');
                          ^
TypeError: Cannot read property 'state' of null

**Comment by frenck** [comment]
Hi @leapp,

Thank you for your issue. Nevertheless, this seems to be an issue with the homebridge-homeassistant plugin this addon is using and is out of scope for this add-on.

Please file an issue here: https://github.com/home-assistant/homebridge-homeassistant

PS: v2.0.0 of the add-on is out already, which might solve the issue since it contains an upgraded version of Homebridge and its plugins.
